version: '3.5'
services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=12345
    volumes:
      - /srv/docker/volumes/graficos/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - backend
    #labels:
    # - "traefik.enable=false"
    # - "container_group=TIG"

  telegraf:
    image: telegraf
    environment:
      HOST_PROC: '/rootfs/proc'
      HOST_SYS: '/rootfs/sys'
      HOST_ETC: '/rootfs/etc'
    volumes:
      - /srv/docker/volumes/graficos/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /run:/rootfs/run:ro
      - /etc:/rootfs/etc:ro
    links:
      - influxdb
    networks:
      - backend
    deploy:
      mode: global
    #labels:
        #- "traefik.enable=false"
        #- "container_group=TIG"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.jfbenito.lan
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=jfbenito.lan
    volumes:
      - /srv/docker/volumes/graficos/grafana:/var/lib/grafana
    networks:
      - proxy
      - backend
    ports:
      - 3000:3000
    deploy:
      labels:
     #- "traefik.backend=tick"
        - "traefik.frontend.rule=Host:grafana.jfbenito.lan"
        - "traefik.docker.network=proxy"
        - "traefik.port=3000"
     #- "container_group=TIG"

networks:
  backend:
  proxy:
    external: True
