version: '3.4'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/volumes/portainer/data:/srv/docker/volumes/portainer/data
    deploy:
      labels:
         traefik.port: 9000
         traefik.frontend.rule: "Host:portainer.jfbenito.lan"
         traefik.docker.network: 'proxy'
    networks:
       - proxy
networks:
  proxy:
    external: true
