version: "3.4"
services:

#      - "--acme.storage=traefik/acme/account"
  traefik_init:
    image: traefik:1.5
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80" #Redirect.EntryPoint:https"
        #- "--entrypoints=Name:https " #Address::443 TLS"
      - "--defaultentrypoints=http" #,https"
        #- "--acme"
        #- "--acme.entryPoint=https"
        #- "--acme.httpChallenge.entryPoint=http"
        #- "--acme.OnHostRule=true"
        #- "--acme.onDemand=false"
        #- "--acme.email="
        #- "--acme.storage=traefik/acme/account"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=jfbenito.lan"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=http://consul:8500"
        #- "--consul.prefix=traefik"
    networks:
      - proxy
      - consul
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul

  traefik:
    image: traefik:1.5
    depends_on:
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=http://consul:8500"
        #- "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
      - consul
    ports:
      - target: 80
        published: 80
        mode: host
        #- target: 443
        # published: 443
        #mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
  consul:
          external: true
